
auto: false
permalink: /:year/:month/:day/:title
pygments: true
markdown:    rdiscount
paginate: 20
rdiscount:
  extensions: []



# Use henrik-jekyll that has the haml/sass extension for this site.
sass: true
haml: true

post_defaults: 
  layout: post
