multivews: true

source:         .
destination:    ./_site
includes:       ./_includes

pygments:       true
markdown:       kramdown
permalink:      /:year/:month/:day/:title

name: 	        blay.se
base_url:       http://blay.se
description:    "blog" 
root_desc:      "blay.se"

exclude: ['Rakefile', 'README.markdown', 'config.rb']
